apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oliver
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: frontend
      ports:
        - name: http
          port: 3000
      publicPort: http
      src: .